### ISSUE TITLE
Cannot update a component (`Tags`) while rendering a different component (`i`).

### ISSUE THREAD

**Issue by Liuninggithub** [neohan666/react-router-waiter#11]
onRouteBefore中使用redux的useDispatch()会报警告
![image](https://user-images.githubusercontent.com/19684404/168786564-e8f61e24-c2ac-4b90-9cd1-face2d529d43.png)
代码如下：
![image](https://user-images.githubusercontent.com/19684404/168786697-bf3f4381-9af1-4849-8e99-f4e39d356a23.png)

代码注释掉就不报错了；但是只是warning；没有影响业务；看着不舒服；
![image](https://user-images.githubusercontent.com/19684404/168787166-9e3f3dfa-3e26-476a-a007-92760deb395b.png)

**Comment by neohan666** [comment]
报错信息顾名思义，不能在渲染一个组件时更改该组件，我这里的路由拦截是路由前置钩子，拦截处理时路由还未加载，这是react的警告，不是此插件要考虑的问题。建议修改dispatch里的逻辑，数据更新时不要响应式地触发路由组件的重渲染。
