### ISSUE TITLE
Uncaught Error: useRoutes() may be used only in the context of a <Router> component.

### ISSUE THREAD

**Issue by moyan0531** [neohan666/react-router-waiter#12]
![image](https://user-images.githubusercontent.com/89899073/169509797-5b7a0213-43e4-46d6-8b5c-25dd507d475b.png)
![image](https://user-images.githubusercontent.com/89899073/169509949-8b31f2ab-61f8-471c-9894-983f7eaa9e57.png)
外面包裹了Router确报这个错误为什么呢?

**Comment by neohan666** [comment]
react-router的useRoutes api 只能在被react-router官方路由组件直接包裹下使用，我这个插件是支持直接配置loading效果组件的，直接加个loading属性就行，readme文档里有。
