### ISSUE TITLE
[feature]onRouteBefore回调参数增加上级路由的location对象

### ISSUE THREAD

**Issue by africa1207** [neohan666/react-router-waiter#14]
```
interface OnRouteBeforeType {
  (payload: {
    pathname: string;
    meta: MetaType;
    fromLocation: Location
  }): OnRouteBeforeResType | Promise<OnRouteBeforeResType>;
}
```
场景：当重定向到/login的时候需要带入当前页面和参数，便于login成功后进行回跳

**Comment by neohan666** [comment]
onRouteBefore执行的时候还未进入下一路由，直接window.location获取的就是当前路由，也就是你说的上级路由。

我的另一开源项目里有类似需求的处理方式可以参考，https://github.com/neohan666/react-antd-mobx-admin/blob/master/src/router/index.tsx

后续会考虑对插件做进一步的封装
