### ISSUE TITLE
reacr-router-dom v6版本的，使用这个库出现呢这个异常，请问一下是什么原因导致的？

### ISSUE THREAD

**Issue by gitrunfeng** [neohan666/react-router-waiter#4]
![image](https://user-images.githubusercontent.com/46260012/159014868-cb36f2dd-bc1d-4f96-b98f-cd9234081d75.png)

The above error occurred in one of your React components:
    in Unknown (created by d)
    in Suspense (created by d)
    in i (created by d)
    in d (at App.tsx:36)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.tsx:35)
    in div (at App.tsx:34)
    in App (at src/index.tsx:12)
    in QueryClientProvider (at AppProvider.tsx:76)
    in AppProvider (at src/index.tsx:11)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

就只提示上面这段 没说是什么原因导致的

**Comment by neohan666** [comment]
#3
