### ISSUE TITLE
警告:No routes matched location "/" 

### ISSUE THREAD

**Issue by lxy-Jason** [neohan666/react-router-waiter#5]
刚开始用react,不太熟,用你的这个插件控制台警告No routes matched location "/" 
页面为空白,我不知道哪里的问题,请帮我看看
![image](https://user-images.githubusercontent.com/94227696/159386417-f4db20c3-e5c9-431c-a70a-aa594b26e2c3.png)
![image](https://user-images.githubusercontent.com/94227696/159386479-f66e6db9-3de2-4a75-a24d-9705871aa7c5.png)

**Comment by neohan666** [comment]
路由配置数组看起来没问题，/重定向到/login，看看是不是/login页的逻辑或者路由拦截那里的问题，死循环什么的

**Comment by lxy-Jason** [comment]
这是拦截那块,我只改了判断是否登录的逻辑
![image](https://user-images.githubusercontent.com/94227696/159406681-655ec321-93e5-49db-8bf4-9e719f893378.png)
login页面在使用插件之后没做任何更改,之前是能正常显示的
警告的详情
![image](https://user-images.githubusercontent.com/94227696/159406793-c24f4c89-b261-4853-ab95-3141fef5bac6.png)

**Comment by neohan666** [comment]
你报错时的访问地址是什么呢

**Comment by neohan666** [comment]
我知道了，幸亏我眼力好，你RouterWaiter组件使用那里写错了，routes和onRouteBefore应该作为组件属性引入，而你是作为组件插槽内容包起来了。。。

![image](https://user-images.githubusercontent.com/39074445/159434670-af75fc13-324a-4ae1-b699-18a97b613a8a.png)
