### ISSUE TITLE
使用 element 抛错 ？？ 

### ISSUE THREAD

**Issue by lianghw** [neohan666/react-router-waiter#6]
<img width="755" alt="图片" src="https://user-images.githubusercontent.com/29350837/160093013-afe9b548-25c0-41ac-9c94-fad3476e3e29.png">

![图片](https://user-images.githubusercontent.com/29350837/160093535-b50d7231-7db6-4deb-be07-4333d5a544c6.png)

配置路由不能直接使用 element 么？

**Comment by neohan666** [comment]
当然可以使用element，你这是jsx语法校验不支持，不是插件问题，看看你文件后缀名是不是jsx或tsx
