### ISSUE TITLE
引入该库使用，一直出现 TypeError: ctor is not a function 错误

### ISSUE THREAD

**Issue by yutongShe** [neohan666/react-router-waiter#8]
![1649583356(1)](https://user-images.githubusercontent.com/43801252/162612027-0c3a8088-94a2-4173-b4c7-b84e6f84b557.png)
似乎是react-router版本不兼容的问题，更新版本如下后依然报相同的错误，请问是懒加载的部分导致的吗？
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-router-dom": "^6.2.1",
    "react-router-waiter": "^1.1.6",

**Comment by neohan666** [comment]
看下路由配置的方式对不对，component配置属性要使用import()函数

**Comment by yutongShe** [comment]
> 
谢谢，是这个问题，已解决
